#!/usr/bin/env node
/**
 * Decode the stock firmware's IOPORT pin-configuration table.
 *
 * The stock application DOES configure its own pins — an `ioport_cfg_t` at 0x0031E3CC
 * holds {count, *table}, and the table is an array of SSP `ioport_pin_cfg_t`:
 *
 *     struct { uint32_t pin_cfg; ioport_port_pin_t pin; }     // 8 bytes, cfg first
 *
 * `pin` encodes (port << 8) | pin_number. `pin_cfg` is the SSP ioport_cfg_options_t
 * bitfield, whose PSEL (peripheral select) sits in bits 24..27.
 *
 * We need this because our replacement application must apply the same mux — it is NOT
 * inherited from the bootloader, contrary to an earlier reading of the image.
 *
 *   node decode-pinmap.js <fw.bin> [--base 0x100000] [--cfg 0x0031E3CC] [--emit-c]
 *
 * --emit-c writes an SSP-shaped ioport_pin_cfg_t table to stdout, ready to drop into
 * the project in place of the BSP's generated pin configuration.
 */

'use strict';
const fs = require('fs');

const args = process.argv.slice(2);
const file = args[0];
if (!file) {
  console.error('usage: node decode-pinmap.js <image.bin> [--table <hex>] [--count <hex>]');
  process.exit(2);
}
const arg = (name, dflt) => {
  const i = args.indexOf(name);
  return i >= 0 ? parseInt(args[i + 1], 16) : dflt;
};
const BASE = arg('--base', 0x00100000);
const CFG = arg('--cfg', 0x0031e3cc);

const img = fs.readFileSync(file);
const u32 = (a) => img.readUInt32LE(a - BASE);

// SSP ioport_cfg_options_t bits (Synergy IOPORT). PSEL occupies bits 24..27.
const FLAGS = [
  [0x00000001, 'OUT_HIGH'],
  [0x00000004, 'DIR_OUTPUT'],
  [0x00000010, 'PULLUP'],
  [0x00000040, 'NMOS'],
  [0x00000080, 'PMOS'],
  [0x00000400, 'DRIVE_MID'],
  [0x00000800, 'DRIVE_HI_B'],
  [0x00000c00, 'DRIVE_HIGH'],
  [0x00001000, 'EVENT_RISING'],
  [0x00002000, 'EVENT_FALLING'],
  [0x00004000, 'IRQ_ENABLE'],
  [0x00008000, 'ANALOG'],
  [0x00010000, 'PERIPHERAL'],
];

function decodeCfg(cfg) {
  const out = [];
  // drive strength is a 2-bit field; test the composite first so we don't print both halves
  let remaining = cfg;
  if ((cfg & 0x00000c00) === 0x00000c00) { out.push('DRIVE_HIGH'); remaining &= ~0x00000c00; }
  for (const [bit, name] of FLAGS) {
    if (name.startsWith('DRIVE')) continue;
    if ((remaining & bit) === bit && bit !== 0) out.push(name);
  }
  if ((remaining & 0x00000c00) === 0x00000400) out.push('DRIVE_MID');
  const psel = (cfg >>> 24) & 0x1f;
  if (cfg & 0x00010000) out.push(`PSEL=0x${psel.toString(16).toUpperCase()}`);
  if (!(cfg & 0x00010000) && !(cfg & 0x00008000) && !(cfg & 0x00000004)) out.push('INPUT');
  return out.length ? out.join(' | ') : 'none';
}

const count = u32(CFG) & 0xffff;
const table = u32(CFG + 4);
if (!(count > 0 && count < 512)) throw new Error(`implausible pin count ${count}`);
if (!(table >= BASE && table < BASE + img.length)) throw new Error(`table ptr 0x${table.toString(16)} out of image`);

const emitC = args.includes('--emit-c');

if (emitC) {
  // SSP-shaped table, ready to replace the BSP's generated pin configuration.
  console.log(`/* Electra One Mini pin configuration.
 *
 * Recovered verbatim from stock firmware v4.1.4: ioport_cfg_t at 0x${CFG.toString(16).toUpperCase()}
 * pointing at ${count} ioport_pin_cfg_t entries at 0x${table.toString(16).toUpperCase()}.
 *
 * The application configures these itself -- it does NOT inherit a muxed board from the
 * bootloader -- so our replacement must apply an equivalent table.
 *
 * pin_cfg is written straight to PmnPFS: SSP's ioport_cfg_options_t bitfield is that
 * register's layout. pin is (port << 8) | pin_number.
 *
 * Generated by tools/pinmap/decode-pinmap.js --emit-c. Do not hand-edit; regenerate.
 */

#include "bsp.h"

const electra_pin_cfg_t g_electra_pin_cfg_data[] = {`);
  for (let i = 0; i < count; i++) {
    const a = table + i * 8;
    const cfg = u32(a);
    const pin = u32(a + 4);
    const port = (pin >>> 8) & 0xff;
    const num = pin & 0xff;
    const label = `P${port.toString(16).toUpperCase()}${num.toString(16).toUpperCase().padStart(2, '0')}`;
    const entry = `    { 0x${cfg.toString(16).padStart(8, '0').toUpperCase()}UL, `
      + `0x${pin.toString(16).padStart(4, '0').toUpperCase()}UL },`;
    console.log(`${entry.padEnd(42)} /* ${label}  ${decodeCfg(cfg)} */`);
  }
  console.log(`};

const uint32_t g_electra_pin_cfg_count = ${count};`);
  process.exit(0);
}

console.log(`ioport_cfg_t @0x${CFG.toString(16)}  count=${count}  table=0x${table.toString(16)}\n`);
console.log('  PIN     cfg         decoded');
console.log('  ------  ----------  ---------------------------------------------');

const byPsel = new Map();
const rows = [];
for (let i = 0; i < count; i++) {
  const a = table + i * 8;
  const cfg = u32(a);
  const pin = u32(a + 4);
  const port = (pin >>> 8) & 0xff;
  const num = pin & 0xff;
  if (port > 11 || num > 15) throw new Error(`entry ${i}: implausible pin 0x${pin.toString(16)}`);
  const name = `P${port.toString(16).toUpperCase()}${num.toString(16).toUpperCase().padStart(2, '0')}`;
  const dec = decodeCfg(cfg);
  rows.push({ name, cfg, dec, port });
  console.log(`  ${name.padEnd(6)}  0x${cfg.toString(16).padStart(8, '0')}  ${dec}`);

  const key = (cfg & 0x00010000) ? `PSEL=0x${((cfg >>> 24) & 0x1f).toString(16).toUpperCase()}`
    : (cfg & 0x00008000) ? 'ANALOG'
      : (cfg & 0x00004000) ? 'IRQ'
        : (cfg & 0x00000004) ? 'GPIO_OUT' : 'GPIO_IN';
  if (!byPsel.has(key)) byPsel.set(key, []);
  byPsel.get(key).push(name);
}

console.log(`\n\nGrouped by function (${count} pins configured):\n`);
for (const [k, pins] of [...byPsel.entries()].sort()) {
  console.log(`  ${k.padEnd(11)} (${String(pins.length).padStart(2)})  ${pins.join(' ')}`);
}
