/* Electra One Mini pin configuration.
 *
 * Recovered verbatim from stock firmware v4.1.4: ioport_cfg_t at 0x31E3CC
 * pointing at 100 ioport_pin_cfg_t entries at 0x31E0AC.
 *
 * The application configures these itself -- it does NOT inherit a muxed board from the
 * bootloader -- so our replacement must apply an equivalent table.
 *
 * pin_cfg is written straight to PmnPFS: SSP's ioport_cfg_options_t bitfield is that
 * register's layout. pin is (port << 8) | pin_number.
 *
 * Generated by tools/pinmap/decode-pinmap.js --emit-c. Do not hand-edit; regenerate.
 */

#include "bsp.h"

const electra_pin_cfg_t g_electra_pin_cfg_data[] = {
    { 0x00004000UL, 0x0000UL },            /* P000  IRQ_ENABLE | INPUT */
    { 0x00004000UL, 0x0001UL },            /* P001  IRQ_ENABLE | INPUT */
    { 0x00004000UL, 0x0002UL },            /* P002  IRQ_ENABLE | INPUT */
    { 0x00000000UL, 0x0003UL },            /* P003  INPUT */
    { 0x00004000UL, 0x0004UL },            /* P004  IRQ_ENABLE | INPUT */
    { 0x00004000UL, 0x0005UL },            /* P005  IRQ_ENABLE | INPUT */
    { 0x00008000UL, 0x000EUL },            /* P00E  ANALOG */
    { 0x00008000UL, 0x000FUL },            /* P00F  ANALOG */
    { 0x0B010C00UL, 0x0100UL },            /* P100  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0101UL },            /* P101  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0102UL },            /* P102  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0103UL },            /* P103  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0104UL },            /* P104  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0105UL },            /* P105  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0106UL },            /* P106  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0107UL },            /* P107  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x00010000UL, 0x0108UL },            /* P108  PERIPHERAL | PSEL=0x0 */
    { 0x05010000UL, 0x0109UL },            /* P109  PERIPHERAL | PSEL=0x5 */
    { 0x05010000UL, 0x010AUL },            /* P10A  PERIPHERAL | PSEL=0x5 */
    { 0x0B010C00UL, 0x010BUL },            /* P10B  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x010CUL },            /* P10C  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x010DUL },            /* P10D  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x010EUL },            /* P10E  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x010FUL },            /* P10F  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x00004000UL, 0x0200UL },            /* P200  IRQ_ENABLE | INPUT */
    { 0x00000000UL, 0x0201UL },            /* P201  INPUT */
    { 0x06010000UL, 0x0202UL },            /* P202  PERIPHERAL | PSEL=0x6 */
    { 0x06010000UL, 0x0203UL },            /* P203  PERIPHERAL | PSEL=0x6 */
    { 0x06010000UL, 0x0204UL },            /* P204  PERIPHERAL | PSEL=0x6 */
    { 0x15010C10UL, 0x0205UL },            /* P205  DRIVE_HIGH | PULLUP | PERIPHERAL | PSEL=0x15 */
    { 0x15010C10UL, 0x0206UL },            /* P206  DRIVE_HIGH | PULLUP | PERIPHERAL | PSEL=0x15 */
    { 0x06010000UL, 0x0207UL },            /* P207  PERIPHERAL | PSEL=0x6 */
    { 0x00010000UL, 0x0300UL },            /* P300  PERIPHERAL | PSEL=0x0 */
    { 0x0B010C00UL, 0x0301UL },            /* P301  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0302UL },            /* P302  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0303UL },            /* P303  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0304UL },            /* P304  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0305UL },            /* P305  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0306UL },            /* P306  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0307UL },            /* P307  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0308UL },            /* P308  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0309UL },            /* P309  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x030AUL },            /* P30A  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x030BUL },            /* P30B  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x030CUL },            /* P30C  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x00000005UL, 0x030DUL },            /* P30D  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x030EUL },            /* P30E  OUT_HIGH | DIR_OUTPUT */
    { 0x07010000UL, 0x0400UL },            /* P400  PERIPHERAL | PSEL=0x7 */
    { 0x07010000UL, 0x0401UL },            /* P401  PERIPHERAL | PSEL=0x7 */
    { 0x00000004UL, 0x0402UL },            /* P402  DIR_OUTPUT */
    { 0x00000004UL, 0x0403UL },            /* P403  DIR_OUTPUT */
    { 0x00000005UL, 0x0404UL },            /* P404  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0405UL },            /* P405  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0406UL },            /* P406  OUT_HIGH | DIR_OUTPUT */
    { 0x13010000UL, 0x0407UL },            /* P407  PERIPHERAL | PSEL=0x13 */
    { 0x05010000UL, 0x0408UL },            /* P408  PERIPHERAL | PSEL=0x5 */
    { 0x05010000UL, 0x0409UL },            /* P409  PERIPHERAL | PSEL=0x5 */
    { 0x15010C10UL, 0x040AUL },            /* P40A  DRIVE_HIGH | PULLUP | PERIPHERAL | PSEL=0x15 */
    { 0x15010C10UL, 0x040BUL },            /* P40B  DRIVE_HIGH | PULLUP | PERIPHERAL | PSEL=0x15 */
    { 0x15010C10UL, 0x040CUL },            /* P40C  DRIVE_HIGH | PULLUP | PERIPHERAL | PSEL=0x15 */
    { 0x15010C00UL, 0x040DUL },            /* P40D  DRIVE_HIGH | PERIPHERAL | PSEL=0x15 */
    { 0x15010C00UL, 0x040EUL },            /* P40E  DRIVE_HIGH | PERIPHERAL | PSEL=0x15 */
    { 0x11010000UL, 0x0500UL },            /* P500  PERIPHERAL | PSEL=0x11 */
    { 0x11010000UL, 0x0501UL },            /* P501  PERIPHERAL | PSEL=0x11 */
    { 0x11010000UL, 0x0502UL },            /* P502  PERIPHERAL | PSEL=0x11 */
    { 0x11010000UL, 0x0503UL },            /* P503  PERIPHERAL | PSEL=0x11 */
    { 0x04010000UL, 0x0505UL },            /* P505  PERIPHERAL | PSEL=0x4 */
    { 0x04010000UL, 0x0506UL },            /* P506  PERIPHERAL | PSEL=0x4 */
    { 0x07010000UL, 0x050BUL },            /* P50B  PERIPHERAL | PSEL=0x7 */
    { 0x07010000UL, 0x050CUL },            /* P50C  PERIPHERAL | PSEL=0x7 */
    { 0x00000005UL, 0x050DUL },            /* P50D  OUT_HIGH | DIR_OUTPUT */
    { 0x0B010C00UL, 0x0601UL },            /* P601  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0602UL },            /* P602  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0603UL },            /* P603  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0604UL },            /* P604  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0605UL },            /* P605  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x00000005UL, 0x0606UL },            /* P606  OUT_HIGH | DIR_OUTPUT */
    { 0x00000004UL, 0x0607UL },            /* P607  DIR_OUTPUT */
    { 0x0B010C00UL, 0x0608UL },            /* P608  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0609UL },            /* P609  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x060AUL },            /* P60A  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x060BUL },            /* P60B  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x060CUL },            /* P60C  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x060DUL },            /* P60D  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x060EUL },            /* P60E  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x00000005UL, 0x0700UL },            /* P700  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0701UL },            /* P701  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0702UL },            /* P702  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0703UL },            /* P703  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0704UL },            /* P704  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0705UL },            /* P705  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0706UL },            /* P706  OUT_HIGH | DIR_OUTPUT */
    { 0x00004010UL, 0x0707UL },            /* P707  PULLUP | IRQ_ENABLE | INPUT */
    { 0x0B010C00UL, 0x0800UL },            /* P800  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x0B010C00UL, 0x0801UL },            /* P801  DRIVE_HIGH | PERIPHERAL | PSEL=0xB */
    { 0x00000005UL, 0x0900UL },            /* P900  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0901UL },            /* P901  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0905UL },            /* P905  OUT_HIGH | DIR_OUTPUT */
    { 0x00000005UL, 0x0B00UL },            /* PB00  OUT_HIGH | DIR_OUTPUT */
    { 0x14010000UL, 0x0B01UL },            /* PB01  PERIPHERAL | PSEL=0x14 */
};

const uint32_t g_electra_pin_cfg_count = 100;
