/* Antialiased bitmap fonts, blended on the MCU.
 *
 * Glyphs are 8-bit coverage cropped to their ink box, generated by tools/font/make-font.py.
 * The renderer blends coverage against caller-supplied colours, so one atlas serves any colour
 * pair and the result is antialiased — which the RA8876's own 1-bit text and BTE glyph blitting
 * cannot give.
 *
 * The cost is that text pixels travel over SPI rather than being composited in VRAM. That is
 * affordable exactly because text is small: cost scales with ink, not with screen area.
 */

#ifndef ELECTRA_FONT_H
#define ELECTRA_FONT_H

#include <stdint.h>

typedef struct {
    uint32_t off;        /* into the face's pixel blob */
    uint8_t  w, h;       /* ink box */
    int8_t   bx, by;     /* bearing: left of the pen, and down from the TOP of the line box */
    uint8_t  adv;        /* pen advance */
} font_glyph_t;

typedef struct {
    const uint8_t      *pixels;
    const font_glyph_t *glyphs;
    uint8_t  first, last;
    uint8_t  ascent, descent, line_height;
} font_t;

extern const font_t font_ui;      /* proportional, labels */
extern const font_t font_value;   /* monospaced, numbers that must not jitter */
extern const font_t font_small;   /* proportional, units and secondary text */
extern const font_t font_display; /* the focused readout; digits and punctuation only */
extern const font_t font_icons;   /* Segoe MDL2, remapped to bytes; see icons.h */

#endif /* ELECTRA_FONT_H */
